AWSTemplateFormatVersion: 2010-09-09
Parameters:
 VpcId:
  Description: Select your vpc id.
  Type: AWS::EC2::VPC::Id
 SubnetId:
  Description: Select your subnet id that exist in your selected vpc.
  Type: AWS::EC2::Subnet::Id
 KeyName:
  Description: Select your key pair.
  Type: AWS::EC2::Keypair::KeyName
 YYYYMMDD:
  Description: Input a today's data. ex)20221111 
  Type: String
 HandsonName:
  Description: Input a handson name. Do not change as much as possible.
  Type: String
  Default: chn-handson
  AllowedValues: 
   - chn-handson
 InstanceName:
  Description: Input a instance name. Do not change as much as possible.
  Type: String
  Default: web 
  AllowedValues:
   - web
Resources: 
 WebServer:
  Type: AWS::EC2::Instance
  Properties:
   BlockDeviceMappings:
    - DeviceName: /dev/xvda
      Ebs:
       VolumeSize: 8
       VolumeType: gp2
       DeleteOnTermination: true
   ImageId: ami-09d3b3274b6c5d4aa
   InstanceType: t2.micro
   KeyName: !Ref KeyName
   NetworkInterface:
    - AssociatePublicIpAddress: true
      DeleteOnTermination: true
      GroupSet:
       - !Ref WebSG
      DeviceIndex: 0
      SubnetId: !Ref SubnetId
   Tags:
    - Key: Nmae
      Value: !Sub ${YYYYMMDD}-${HandsonName}-${InstanceName}
   UserData: String
 WebSG:
  Type: AWS::EC2::SecurityGroup
  Properties:
   GroupDescripton: !Sub Security Group attached to ${YYYYMMDD}-${HandsonName}-${InstanceName}
   GroupName: !Sub sg_${YYYYMMDD}-${HandsonName}-${InstanceName}
   GroupName: String
   SecurityGroupIngress: 
    - CidrIp: 0.0.0.0/0
      Description: SSH port
      FromPort: 22
      IpProtocol: tcp
      ToPort: 22
    - CidrIp: 0.0.0.0/0
      Description: HTTP Port
      FromPort: 80
      IpProtocol: tcp
      ToPort: 80
   VpcId: !Ref VpcId
   